### ISSUE TITLE
Enable https

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/university-of-remainia#20]
This will help with SEO and the like. It can be done rather easily through netlify, and will likely involve me going around and removing inline-styles and putting them in a Sass document, as well as minifying the javascript. 

I think this should be done before launch.

**Comment by RichardLitt** [comment]
@cameronneylon Could you add the DNS records to the domain, so that I can add SSL on Netlify? https://www.netlify.com/docs/custom-domains/#dns-configuration

**Comment by RichardLitt** [comment]
I went through this process a couple of weeks ago, here, too: https://github.com/RichardLitt/knowledge/blob/master/ssl-security.md. Explains my reasoning.

**Comment by cameronneylon** [comment]
Added the A record to the load balancer IP as that seemed the easiest way to make it work based on the docs.

**Comment by RichardLitt** [comment]
It looks like the A records for GitHub are still there; can you remove those, too? 

```
  dig british-research-in.eu

; <<>> DiG 9.8.3-P1 <<>> british-research-in.eu
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62825
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;british-research-in.eu.		IN	A

;; ANSWER SECTION:
british-research-in.eu.	14400	IN	A	192.30.252.153
british-research-in.eu.	14400	IN	A	104.198.14.52
british-research-in.eu.	14400	IN	A	192.30.252.154

;; Query time: 52 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Sun Nov 27 07:53:24 2016
;; MSG SIZE  rcvd: 88


```

**Comment by cameronneylon** [comment]
Fixed I think.

**Comment by RichardLitt** [comment]
I think this is done! I'm still seeing the 192 GitHub A records. Those can be removed; if you have, they may just need to propagate. Reopen if they cause an issue.
